GlobalVars:
  AllowedVariables:
    - $boards
    - $turn

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 50

# Metrics/AbcSize:
#   Enabled: false


Metrics/CyclomaticComplexity:
  Max: 15
  
# Metrics/CyclomaticComplexity:
#   Enabled: false



Metrics/PerceivedComplexity:
  Max: 15

# Metrics/PerceivedComplexity:
#   Enabled: false


# Rubocop: Default Configured Maximums
# The default configured maximums for:
# Cyclomatic complexity is 6.
# Perceived complexity is 7.
# The ABC metric is 15.

